// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmapbKDB01zpnrSMyqoO3nO_Gv98y4bAw',
    appId: '1:924791508157:web:b5b3cd263dc43707577bd4',
    messagingSenderId: '924791508157',
    projectId: 'word-f43ac',
    authDomain: 'word-f43ac.firebaseapp.com',
    databaseURL: 'https://word-f43ac-default-rtdb.firebaseio.com',
    storageBucket: 'word-f43ac.appspot.com',
    measurementId: 'G-3HBGL37XMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZppdx6xLW-IlL-0KqrztT3cye9EaOG90',
    appId: '1:924791508157:android:278b60b338667907577bd4',
    messagingSenderId: '924791508157',
    projectId: 'word-f43ac',
    databaseURL: 'https://word-f43ac-default-rtdb.firebaseio.com',
    storageBucket: 'word-f43ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xEAjyHgMDNlrga1ic7JBGBv06bDgb9I',
    appId: '1:924791508157:ios:e475c5bdb86b302c577bd4',
    messagingSenderId: '924791508157',
    projectId: 'word-f43ac',
    databaseURL: 'https://word-f43ac-default-rtdb.firebaseio.com',
    storageBucket: 'word-f43ac.appspot.com',
    androidClientId: '924791508157-chbecjsnbe6gqrf9ue4d32fg24nmarp8.apps.googleusercontent.com',
    iosClientId: '924791508157-am8p5k1d0pfego3qu3vu1vid32gudoci.apps.googleusercontent.com',
    iosBundleId: 'com.example.glowUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xEAjyHgMDNlrga1ic7JBGBv06bDgb9I',
    appId: '1:924791508157:ios:e475c5bdb86b302c577bd4',
    messagingSenderId: '924791508157',
    projectId: 'word-f43ac',
    databaseURL: 'https://word-f43ac-default-rtdb.firebaseio.com',
    storageBucket: 'word-f43ac.appspot.com',
    androidClientId: '924791508157-chbecjsnbe6gqrf9ue4d32fg24nmarp8.apps.googleusercontent.com',
    iosClientId: '924791508157-am8p5k1d0pfego3qu3vu1vid32gudoci.apps.googleusercontent.com',
    iosBundleId: 'com.example.glowUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmapbKDB01zpnrSMyqoO3nO_Gv98y4bAw',
    appId: '1:924791508157:web:c8f8d8e96fda92d3577bd4',
    messagingSenderId: '924791508157',
    projectId: 'word-f43ac',
    authDomain: 'word-f43ac.firebaseapp.com',
    databaseURL: 'https://word-f43ac-default-rtdb.firebaseio.com',
    storageBucket: 'word-f43ac.appspot.com',
    measurementId: 'G-0S45Q65041',
  );

}