// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRM82jWC_PUIstNbPP26Dj7ShwKvPUSk',
    appId: '1:93874100060:web:6fc79b0c12d263f9e9d399',
    messagingSenderId: '93874100060',
    projectId: 'glowup-c53d2',
    authDomain: 'glowup-c53d2.firebaseapp.com',
    storageBucket: 'glowup-c53d2.firebasestorage.app',
    measurementId: 'G-C1SL2KTFM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqg1F8Q3mEfMB-7LZdhweQhLIvgOd-srQ',
    appId: '1:93874100060:android:a6cd403370900a39e9d399',
    messagingSenderId: '93874100060',
    projectId: 'glowup-c53d2',
    storageBucket: 'glowup-c53d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkOmwrjnZ_P5zAaAWxUwvseHpVGgx4OrA',
    appId: '1:93874100060:ios:a436831101ff8ba0e9d399',
    messagingSenderId: '93874100060',
    projectId: 'glowup-c53d2',
    storageBucket: 'glowup-c53d2.firebasestorage.app',
    iosClientId: '93874100060-s8f65kgcfnu13sv65uupel5bt4kb373m.apps.googleusercontent.com',
    iosBundleId: 'com.example.glowUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkOmwrjnZ_P5zAaAWxUwvseHpVGgx4OrA',
    appId: '1:93874100060:ios:a436831101ff8ba0e9d399',
    messagingSenderId: '93874100060',
    projectId: 'glowup-c53d2',
    storageBucket: 'glowup-c53d2.firebasestorage.app',
    iosClientId: '93874100060-s8f65kgcfnu13sv65uupel5bt4kb373m.apps.googleusercontent.com',
    iosBundleId: 'com.example.glowUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeRM82jWC_PUIstNbPP26Dj7ShwKvPUSk',
    appId: '1:93874100060:web:1a13da0bf9575135e9d399',
    messagingSenderId: '93874100060',
    projectId: 'glowup-c53d2',
    authDomain: 'glowup-c53d2.firebaseapp.com',
    storageBucket: 'glowup-c53d2.firebasestorage.app',
    measurementId: 'G-LJ7WNSN8PS',
  );
}
